spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/annotationtool
    username: annotation_user
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false