spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/annotationtool
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
  servlet:
    multipart:
      max-file-size: 5MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework.security: DEBUG

application:
  storage:
    upload-default-path: "D:/Diploma/annotation-image-storage/{projectId}/images"
    upload-preview-path: "D:/Diploma/annotation-image-storage/{projectId}/preview"

STRIPE_PUBLIC_KEY: sk_test_51MxXxKDn9IcXEBBEBUuTSyPgJ3lCWzARZsHgg0TxRw9L3j63MGtvcSywGNa3CWZNqzPcLsIjS63IjXQitc3aqjgd00FAoRcPKO