spring:
  datasource:
    host: localhost:5432
    dbname: annotationtool
    url: jdbc:postgresql://${spring.datasource.host}/${spring.datasource.dbname}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
  servlet:
    multipart:
      max-file-size: 5MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework.security: DEBUG

application:
  storage:
    base-path: "D:/Diploma/annotation-image-storage"
    upload-default-path: "${application.storage.base-path}/{projectId}/images"
    upload-preview-path: "${application.storage.base-path}/{projectId}/preview"

STRIPE_PUBLIC_KEY: sk_test_51MxXxKDn9IcXEBBEBUuTSyPgJ3lCWzARZsHgg0TxRw9L3j63MGtvcSywGNa3CWZNqzPcLsIjS63IjXQitc3aqjgd00FAoRcPKO