
services:
  image-annotation-be:
    image: paulthestrong/image-annotation-be:1.0.1
    volumes:
      - image-data:/image-data
    environment:
      SPRING_DATASOURCE_HOST: postgres-image-annotation-be
      APPLICATION_STORAGE_BASE_PATH: /image-data
  postgres-image-annotation-be:
    image: postgres:15.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: annotationtool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  pgadmin4:
    image: dpage/pgadmin4:7.5
    ports:
      - 5050:80
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: 12345678


volumes:
  image-data:
  pgdata:

networks:
  back-end:
