name: build-push-docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker-hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Checkstyle with maven
        run: mvn checkstyle:check
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build docker image
        run: mvn spring-boot:build-image
      - name: Export version variable
        run: export APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Tag docker image
        run: docker tag image-annotation-be:$APP_VERSION ${{ secrets.DOCKER_USERNAME }}/image-annotation-be:$APP_VERSION
      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/image-annotation-be:$APP_VERSION

