name: build-and-test
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Checkstyle with maven
        run: mvn checkstyle:check
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.JACOCO_GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60