name: build-push-docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Checkstyle with maven
        run: mvn checkstyle:check
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build docker image
        run: mvn spring-boot:build-image
      - name: Login to docker-hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

